############### SHELL ###############

[git.files]
git = "~/.config/git"

[git.variables]
git_credential = "osxkeychain"
git_username = "YOUR_NAME"
git_email = "YOUR_EMAIL"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zsh_plugins.txt" = "~/.zsh_plugins.txt"

[tmux.files]
tmux = "~/.config/tmux"

[neovim.files]
nvim = { type = "symbolic", target="~/.config/nvim", recurse = false }

[ranger.files]
ranger = "~/.config/ranger"

[herdr.files]
"herdr/config.toml" = "~/.config/herdr/config.toml"


############### GUI ###############

[alacritty.files]
alacritty = "~/.config/alacritty"

[kitty.files]
kitty = { type = "symbolic", target = "~/.config/kitty", recurse = false }

[ghostty.files]
ghostty = "~/.config/ghostty"

[karabiner.files]
# create folder symlink instead of files symlink
karabiner = { type = "symbolic", target="~/.config/karabiner", recurse = false }

[mpv.files]
mpv = "~/.config/mpv"

[mpv.variables]
# options: "default-cache", "big-cache"
cache_profile = "default-cache"

[zathura.files]
zathura = "~/.config/zathura"

[aerospace.files]
aerospace = "~/.config/aerospace"
