############### SHELL ###############

[git.files]
git = "~/.config/git"

[git.variables]
git_credential = "osxkeychain"
git_username = "YOUR_NAME"
git_email = "YOUR_EMAIL"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[zsh.variables]
zsh_theme = "ys"

[tmux.files]
tmux = "~/.config/tmux"

[neovim.files]
nvim = { type = "symbolic", target="~/.config/nvim", recurse = false }

[ranger.files]
ranger = "~/.config/ranger"


############### GUI ###############

[alacritty.files]
alacritty = "~/.config/alacritty"

[karabiner.files]
# create folder symlink instead of files symlink
karabiner = { type = "symbolic", target="~/.config/karabiner", recurse = false }

[phoenix.files]
phoenix = "~/.config/phoenix"

[mpv.files]
mpv = "~/.config/mpv"

[mpv.variables]
# options: "default-cache", "big-cache"
cache_profile = "default-cache"

[zathura.files]
zathura = "~/.config/zathura"

[aerospace.files]
aerospace = "~/.config/aerospace"
